apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: prod
spec:
  encryptedData:
    password: AgAhm3gYAgIU5MVZHWiRXCyo6dZ6TAzWcZKR+YmNs/GhP8oXj0aifk+vOxZhMvnLw2MCbvLJM8qXZhKuRKOBFCH6SqBFFYCVmwahBoCGZNRO7E+GFvOpKsjun2l1XUtz79mvP2ERL6oFPaq0TgfgGxQaxcLCNXppdertw6mkQeMGElWqolH9GLL97MwBHE/mU+um6x5r7TylcJRHtOR1c7bWXqiYvth/DNx2Pgr+TFql6Px8NPHd1Rvs7VoW//ihGvXp484qA0oiu5TEzwVVMl9HwAWlHctle8K0VGeZlNagSiqQE0mx2VZf56iZ2CRPDT6An8phEfGcG5fbNWO7yVvaQlAV3CLP8VDAqJsQ3rkzahJRvVCAan3cBNFc16JKSgjkmcIBPHtIq5DJRMHMcR5aQ4lLoaON1Vc6JoVEfxJdIE7d5j5iCDQOwFDmrQJOamyXDDNrQn7j++mE2+4jXH9OVAiW4d90uowzUeImy7yb5AqyOt8Fg/iiLhgX/DxvNtHo4f6DakRXousNDkcySJRpHoIri4TR4hMr+GyY+sy+0+1tY2gcszhSGz+PxBppSgig/HWsSrSIatGDLNsB7tnaypeOk9qA0NJgr21Zwd/V5LS0INH9tcKgQjeKHKl+RB+af6LlHBk51bhxdQXTPaYH1N/C+rbNbReh4c+7TSmBBYFP+HTEP8mzzGSLuhFNQ2uUurkMUQ==
    user: AgBjIO7Id7DqWqZ4RXOTp68No3zomcVrtNaYnJ/iNYiSwKlMAeZVfIIyCys7x3HWtc4HFm+kX5rcGJ2aBMggcV+PF672AWcahnMbVJOI8CNa2S1igAvaBg5UH/0ioSTxTcpSkcjZ/5vC6lh7lfgPxUBqpwTyTGGvXgYLOwt9L2jkR/gxWmUlDGLgG+JLB21QUV5aqXug/h5ds/Rc7qaqszCuc0lpRxhZ/ovy7AesfwrpquNT08GLbaeXCxlEsx4La3szGdqrVEOMQ80bwjdmPlsUnMw0AVSj4tfg8aGZm6KjmU1xHo0bm4vafWma4oHsLsKuXhDp5Vi/uaxufXGvq6O+zSOcX0eSJZXIpc1Aanj2nhX89xcEP7g1vq5t9VKTXEduFibhhcbH3psp63dbz9kgn4TTnjWAkTib3V8P04f7e+3kBVg81dNXyoqVDT4KplxdMNVWlQCWoj7gPNFmWXmB/BGhKOv8/FFgeHeb/ywyPFAn6KRADXegiL/XhEgXFcUckabMlyvobiyh53V6bJOPwNBm1u2+w/IViNuuDTogPc/+2KgTrJZoo2+xOlCb0CLCS72DhEyS40pkBEwoyp3MqGnQIzYPfHnsghQKd5SxDkHcyJm283cPYEEKPCmIfj6pB5fjWHqdAsRUm2hEXuNzPu158vjuEA8aPSN66130OAdeTru4JrDMJXujzoGBLM+7AQjg5A==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: prod
status: {}

